/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    'solicitudes-cita': SolicitudesCita;
    'inscripciones-voluntariado': InscripcionesVoluntariado;
    'inscripciones-padrinos': InscripcionesPadrino;
    'mensajes-contacto': MensajesContacto;
    cuarentena: Cuarentena;
    convocatorias: Convocatoria;
    usuarios: Usuario;
    bitacora: Bitacora;
    'totp-attempts': TotpAttempt;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'solicitudes-cita': SolicitudesCitaSelect<false> | SolicitudesCitaSelect<true>;
    'inscripciones-voluntariado': InscripcionesVoluntariadoSelect<false> | InscripcionesVoluntariadoSelect<true>;
    'inscripciones-padrinos': InscripcionesPadrinosSelect<false> | InscripcionesPadrinosSelect<true>;
    'mensajes-contacto': MensajesContactoSelect<false> | MensajesContactoSelect<true>;
    cuarentena: CuarentenaSelect<false> | CuarentenaSelect<true>;
    convocatorias: ConvocatoriasSelect<false> | ConvocatoriasSelect<true>;
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    bitacora: BitacoraSelect<false> | BitacoraSelect<true>;
    'totp-attempts': TotpAttemptsSelect<false> | TotpAttemptsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solicitudes-cita".
 */
export interface SolicitudesCita {
  id: number;
  nombre: string;
  correo?: string | null;
  telefono?: string | null;
  contactoPreferido: 'whatsapp' | 'telefono' | 'correo';
  motivo?: string | null;
  modalidad: 'cualquiera' | 'virtual' | 'presencial';
  disponibilidad?: string | null;
  atencionPronto?: boolean | null;
  consentimientoEn: string;
  politicaVersion: string;
  estado: 'pendiente' | 'en_gestion' | 'atendida' | 'cerrada_sin_atender';
  atendidaPor?: (number | null) | Usuario;
  atendidaEn?: string | null;
  /**
   * Si está sin marcar, el correo de aviso falló: la solicitud igual está guardada.
   */
  avisoEnviado?: boolean | null;
  /**
   * Solo las ve la administración. No se pueden editar ni borrar después.
   */
  notas?:
    | {
        texto: string;
        autor?: (number | null) | Usuario;
        fecha?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nombre: string;
  rol: 'administrador' | 'editor';
  /**
   * Sin marcar, la cuenta no puede entrar ni ver nada. Una sesión ya abierta caduca en 2 horas como máximo.
   */
  activo?: boolean | null;
  totpSecret?: string | null;
  hasTotp?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscripciones-voluntariado".
 */
export interface InscripcionesVoluntariado {
  id: number;
  nombre: string;
  correo: string;
  telefono?: string | null;
  areasInteres: (
    'redes-sociales' | 'diseno' | 'logistica' | 'psicologia' | 'escritura' | 'transporte' | 'cocina' | 'otra'
  )[];
  otraArea?: string | null;
  disponibilidad?: string | null;
  experiencia?: string | null;
  consentimientoEn: string;
  politicaVersion: string;
  estado: 'pendiente' | 'en_gestion' | 'atendida' | 'cerrada_sin_atender';
  atendidaPor?: (number | null) | Usuario;
  atendidaEn?: string | null;
  /**
   * Si está sin marcar, el correo de aviso falló: la solicitud igual está guardada.
   */
  avisoEnviado?: boolean | null;
  /**
   * Solo las ve la administración. No se pueden editar ni borrar después.
   */
  notas?:
    | {
        texto: string;
        autor?: (number | null) | Usuario;
        fecha?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscripciones-padrinos".
 */
export interface InscripcionesPadrino {
  id: number;
  convocatoria: number | Convocatoria;
  nombre: string;
  correo: string;
  telefono: string;
  cantidadNinos: number;
  formaEntrega: 'llevo' | 'coordinar' | 'asisto';
  comentario?: string | null;
  consentimientoEn: string;
  politicaVersion: string;
  estado: 'pendiente' | 'en_gestion' | 'atendida' | 'cerrada_sin_atender';
  atendidaPor?: (number | null) | Usuario;
  atendidaEn?: string | null;
  /**
   * Si está sin marcar, el correo de aviso falló: la solicitud igual está guardada.
   */
  avisoEnviado?: boolean | null;
  /**
   * Solo las ve la administración. No se pueden editar ni borrar después.
   */
  notas?:
    | {
        texto: string;
        autor?: (number | null) | Usuario;
        fecha?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "convocatorias".
 */
export interface Convocatoria {
  id: number;
  /**
   * El código del proyecto, como aparece en su dirección web.
   */
  proyectoSlug: string;
  tipo: 'padrinos';
  titulo: string;
  descripcion?: string | null;
  textoSiCerrada: string;
  abreEn: string;
  /**
   * Hora de Panamá. Para que cierre al terminar el 15, pon el 16 a las 00:00.
   */
  cierraEn: string;
  cerradaManualmente?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mensajes-contacto".
 */
export interface MensajesContacto {
  id: number;
  nombre: string;
  correo?: string | null;
  telefono?: string | null;
  asunto: string;
  mensaje: string;
  consentimientoEn: string;
  politicaVersion: string;
  estado: 'pendiente' | 'en_gestion' | 'atendida' | 'cerrada_sin_atender';
  atendidaPor?: (number | null) | Usuario;
  atendidaEn?: string | null;
  /**
   * Si está sin marcar, el correo de aviso falló: la solicitud igual está guardada.
   */
  avisoEnviado?: boolean | null;
  /**
   * Solo las ve la administración. No se pueden editar ni borrar después.
   */
  notas?:
    | {
        texto: string;
        autor?: (number | null) | Usuario;
        fecha?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Envíos que llenaron un campo que una persona no ve. Revísalos de vez en cuando por si alguno era real.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuarentena".
 */
export interface Cuarentena {
  id: number;
  formulario: 'solicitudes-cita' | 'inscripciones-voluntariado' | 'inscripciones-padrinos' | 'mensajes-contacto';
  motivo: 'campo_trampa';
  carga:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  revisado?: boolean | null;
  veredicto?: ('robot' | 'persona') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro inalterable de quién vio y quién cambió cada solicitud.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bitacora".
 */
export interface Bitacora {
  id: number;
  accion: 'ver_solicitud' | 'ver_lista' | 'cambiar_estado' | 'borrar_solicitud';
  coleccion: string;
  documento: string;
  usuario?: (number | null) | Usuario;
  correo?: string | null;
  resumen: string;
  datos?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "totp-attempts".
 */
export interface TotpAttempt {
  id: string;
  attempts: number;
  lockUntil?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'solicitudes-cita';
        value: number | SolicitudesCita;
      } | null)
    | ({
        relationTo: 'inscripciones-voluntariado';
        value: number | InscripcionesVoluntariado;
      } | null)
    | ({
        relationTo: 'inscripciones-padrinos';
        value: number | InscripcionesPadrino;
      } | null)
    | ({
        relationTo: 'mensajes-contacto';
        value: number | MensajesContacto;
      } | null)
    | ({
        relationTo: 'cuarentena';
        value: number | Cuarentena;
      } | null)
    | ({
        relationTo: 'convocatorias';
        value: number | Convocatoria;
      } | null)
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'bitacora';
        value: number | Bitacora;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solicitudes-cita_select".
 */
export interface SolicitudesCitaSelect<T extends boolean = true> {
  nombre?: T;
  correo?: T;
  telefono?: T;
  contactoPreferido?: T;
  motivo?: T;
  modalidad?: T;
  disponibilidad?: T;
  atencionPronto?: T;
  consentimientoEn?: T;
  politicaVersion?: T;
  estado?: T;
  atendidaPor?: T;
  atendidaEn?: T;
  avisoEnviado?: T;
  notas?:
    | T
    | {
        texto?: T;
        autor?: T;
        fecha?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscripciones-voluntariado_select".
 */
export interface InscripcionesVoluntariadoSelect<T extends boolean = true> {
  nombre?: T;
  correo?: T;
  telefono?: T;
  areasInteres?: T;
  otraArea?: T;
  disponibilidad?: T;
  experiencia?: T;
  consentimientoEn?: T;
  politicaVersion?: T;
  estado?: T;
  atendidaPor?: T;
  atendidaEn?: T;
  avisoEnviado?: T;
  notas?:
    | T
    | {
        texto?: T;
        autor?: T;
        fecha?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inscripciones-padrinos_select".
 */
export interface InscripcionesPadrinosSelect<T extends boolean = true> {
  convocatoria?: T;
  nombre?: T;
  correo?: T;
  telefono?: T;
  cantidadNinos?: T;
  formaEntrega?: T;
  comentario?: T;
  consentimientoEn?: T;
  politicaVersion?: T;
  estado?: T;
  atendidaPor?: T;
  atendidaEn?: T;
  avisoEnviado?: T;
  notas?:
    | T
    | {
        texto?: T;
        autor?: T;
        fecha?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mensajes-contacto_select".
 */
export interface MensajesContactoSelect<T extends boolean = true> {
  nombre?: T;
  correo?: T;
  telefono?: T;
  asunto?: T;
  mensaje?: T;
  consentimientoEn?: T;
  politicaVersion?: T;
  estado?: T;
  atendidaPor?: T;
  atendidaEn?: T;
  avisoEnviado?: T;
  notas?:
    | T
    | {
        texto?: T;
        autor?: T;
        fecha?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuarentena_select".
 */
export interface CuarentenaSelect<T extends boolean = true> {
  formulario?: T;
  motivo?: T;
  carga?: T;
  revisado?: T;
  veredicto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "convocatorias_select".
 */
export interface ConvocatoriasSelect<T extends boolean = true> {
  proyectoSlug?: T;
  tipo?: T;
  titulo?: T;
  descripcion?: T;
  textoSiCerrada?: T;
  abreEn?: T;
  cierraEn?: T;
  cerradaManualmente?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  activo?: T;
  totpSecret?: T;
  hasTotp?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bitacora_select".
 */
export interface BitacoraSelect<T extends boolean = true> {
  accion?: T;
  coleccion?: T;
  documento?: T;
  usuario?: T;
  correo?: T;
  resumen?: T;
  datos?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "totp-attempts_select".
 */
export interface TotpAttemptsSelect<T extends boolean = true> {
  id?: T;
  attempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}